default_platform(:ios)

platform :ios do

  desc "Build & upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["API_KEY_PATH"],
      in_house: false
    )

    increment_build_number(
      build_number: latest_testflight_build_number(api_key: api_key) + 1
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV["TEAM_ID"],
      code_sign_identity: "Apple Distribution",
      profile_name: ENV["PROFILE_NAME"],
      targets: ["FlickMatch"]
    )

    build_app(
      scheme: "FlickMatch",
      export_method: "app-store",
      configuration: "Release",
      destination: "generic/platform=iOS",
      xcargs: "ONLY_ACTIVE_ARCH=NO ASSETCATALOG_COMPILER_SKIP_VALIDATIONS=YES",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.flickmatch.app" => ENV["PROFILE_NAME"]
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

end
